---
title: "Coursera - Data Science - John Hopkins"
author: "Greg Foletta"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
---

## Course 1 - The Data Scientist's Toolbox

* [Notes](C1_Data_Scientist_Toolbox/notes.html) - Data science process, types of data analysis, experimental design, big data.

## Course 2 - The R Language

* [Week 1 Notes](C2_R_Programming/w1_notes.html) - Overview of R, data types, data frames, attributes, subsetting.
* [Week 2 Notes](C2_R_Programming/w2_notes.html) - R control structures, for and while loops, functions, scoping rules, dates and times.
* [Week 3 Notes](C2_R_Programming/w3_notes.html) - Loop function, lapply, sapply, apply, tapply, mapply, split, debugging.
* [Week 4 Notes](C2_R_Programming/w4_notes.html) - str() function, simulation, permutation, profiling.

## Course 3 - Getting and Cleaning Data

* [Week 1 Notes](C3_Getting_and_Cleaning_Data/w1_notes.html) - motivations and goals, raw and processed data, subset, joins.
* [Week 2 Notes](C3_Getting_and_Cleaning_Data/w2_notes.html) - reading from MySQL, reading HDFS, webscraping, APIs.
* [Week 3 Notes](C3_Getting_and_Cleaning_Data/w3_notes.html) - summarisation, new variables, reshaping, merging.
* [Week 4 Notes](C3_Getting_and_Cleaning_Data/w4_notes.html) - Fixing character vectors, working with dates.

## Course 4 - Exploratory Data Analysis

* [Week 1 Notes](C4_Exploratory_Data_Analysis/w1_notes.html) - Principles, exploratory graphs, plotting systems, graphics devices.
* [Week 2 Notes](C4_Exploratory_Data_Analysis/w2_notes.html) - Latice plotting system, ggplot2.
* [Week 3 Notes](C4_Exploratory_Data_Analysis/w3_notes.html) - Hierarchical clustering, K-means clustering, dimension reduction, colours and palletes.

## Course 5 - Reproducible Research

* [Week 1 Notes](C5_Reproducible_Research/w1_notes.html) - Concepts and ideas, structure of data analysis
* [Week 2 Notes](C5_Reproducible_Research/w2_notes.html) - Coding standards, RMarkdown, knitr
* [Week 3 Notes](C5_Reproducible_Research/w3_notes.html) - Communicating results, rpubs, reproducible research checklist, evidence based data analysis.
* [Week 4 Notes](C5_Reproducible_Research/w4_notes.html) - Caching computations

## Course 6 - Statistical Inference

* [Week 1 Notes](C6_Statistical_Inference/w1_notes.html) - Probability, CDF and survival functions, quantiles, conditional probability, expected values, sample means.
* [Week 2 Notes](C6_Statistical_Inference/w2_notes.html) - Variability, standard error, distributions, central limit theorem, confidence intervals.
* [Week 3 Notes](C6_Statistical_Inference/w3_notes.html) - T-confidence intervals, hypothesis testing, t-tests, p-values.
* [Week 4 Notes](C6_Statistical_Inference/w4_notes.html) - Power, t-test power, multiple testing, resampling.

## Course 7 - Regression Models

* [Week 1 Notes](C7_Regression_Models/w1_notes.html) - Least Squares, Covariance, Correlation, Regression to the Mean
* [Week 2 Notes](C7_Regression_Models/w2_notes.html) - Interpreting coefficients, residuals, heteroskedacticity, slope and intercept variance, prediction vs slope intervals.
* [Week 3 Notes](C7_Regression_Models/w3_notes.html) - Multivariable linear models, influence measures, variance inflation, nested models.
* [Week 4 Notes](C7_Regression_Models/w4_notes.html) - Generalised linear models, logistic regressions, Poisson regressions.

## Course 8 - Practical Machine Learning

* [Week 1 Notes](C8_Regression_Models/w1_notes.html) - Prediction, Cross-Validation, Types of Errors
